security:
    hide_user_not_found:  false
    
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Cdm\UserBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_ADMIN, ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        #ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    
    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        users_db:
            entity: { class: Cdm\UserBundle\Entity\User, property: email }  
        
    
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
                #always_use_default_target_path: true
                default_target_path: dashboard
            anonymous: ~            
            logout:
                path:   /logout
                target: /login
                
#            remember_me:
#                key:      "%secret%"
#                lifetime: 7200 # 2 hrs in seconds
#                path:     /
#                domain:   ~ # Defaults to the current domain from $_SERVER
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_ADMIN }