<?php

namespace Cdm\UserBundle\Repository;

use Doctrine\ORM\EntityRepository as BaseEntityRepository;
use Cdm\UserBundle\Entity\Entity;
/**
 * EnitityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityRepository extends BaseEntityRepository
{
    public function save(Entity $entity)
    {
        if($entity->getId() == null){
            $entity->setCreated(time()); // new data for persist           
        }
        
        $entity->setUpdated(time());
        
        $this->getEntityManager()->persist($entity);
        
        $this->getEntityManager()->flush();
    }
    
    public function remove(Entity $entity)
    {
       $this->getEntityManager()->remove($entity);
       
       $this->getEntityManager()->flush();               
    }
    
}
