<?php

namespace Cdm\UserBundle\Repository;

use Doctrine\ORM\EntityRepository as BaseEntityRepository;
use Cdm\UserBundle\Entity\Invite;

/**
 * IinviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InviteRepository extends BaseEntityRepository
{    
    public function create(Invite $invite)
    {
        if($invite->getId() == null){
            $invite->setCreated(time()); // new data for presist            
        }
        
        $invite->setUpdated(time());
        
        $this->getEntityManager()->persist($invite);
        
        $this->getEntityManager()->flush();
    }
    
    public function delete(Invite $invite)
    {
        $this->getEntityManager()->remove($invite);
        
        $this->getEntityManager()->flush();
    }
}
