<?php

namespace Cdm\UserBundle\Repository;

use Doctrine\ORM\EntityRepository as BaseEntityRepository;

/**
 * ManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManagerRepository extends BaseEntityRepository
{
}
