<?php

namespace Cdm\UserBundle\Repository;

use Doctrine\ORM\EntityRepository as BaseEntityRepository;
use Cdm\UserBundle\Entity\Role;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends BaseEntityRepository
{
    public function save(Role $role)
    {          
        $this->getEntityManager()->persist($role);
        
        $this->getEntityManager()->flush();
    }
    
    public function remove(Role $role)
    {
    	$this->getEntityManager()->remove($role);
       
       $this->getEntityManager()->flush();        
    }
}
