<?php

namespace Cdm\UserBundle\Repository;

use Doctrine\ORM\EntityRepository as BaseEntityRepository;
use Cdm\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseEntityRepository
{
    public function save(User $user)
    {
        if($user->getId() == null){
            $user->setCreated(time()); // new data for presist
            
        }
        
        $user->setUpdated(time());
        
        $this->getEntityManager()->persist($user);
        
        $this->getEntityManager()->flush();
    }
}
