parameters:
#    cdm_user.example.class: Cdm\UserBundle\Example

services:
#    cdm_user.example:
#        class: %cdm_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
