<?php

namespace Cdm\CommonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadRepository extends EntityRepository
{
}
